sudo: false
dist: trusty
group: stable

language: scala

env:
  matrix:
    - SCRIPTED_TEST="; mimaReportBinaryIssues; test; proguard"

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - curl -L --fail https://github.com/sbt/sbt/releases/download/v1.4.9/sbt-1.4.9.tgz > sbt-1.4.9.tgz
  - tar zxf ./sbt-1.4.9.tgz -C $HOME/
  - export PATH="$HOME/sbt/bin:$PATH"
  - export SBT_OPTS="-Xms2048M -Xmx2048M -Xss2M -XX:MaxPermSize=512M"
  - sbt about

# Undo _JAVA_OPTIONS environment variable
before_script:
  - unset _JAVA_OPTIONS

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "$SCRIPTED_TEST"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk
